// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//  https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:page-layout: guide
:projectid: bean-validation
:page-duration: 20 minutes
:page-releasedate: 2018-02-05
:page-description: Learn how to get started with Bean Validation and Open Liberty.
:page-tags: ['Java', 'Getting Started']
:page-related-guides: ['']
:page-permalink: /guides/{projectid}
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating an application with Bean Validation

You'll explore how to create an application using Bean Validation 2.0 in Open Liberty.

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

You will learn the basics of writing an application that uses Bean Validation, the new functionality in Bean Validation 2.0, and how to test an application that uses Bean Validation.

=== What is Bean validation

Bean Validation is a Java Specification allowing data stored in JavaBeans to be validated in a standard way. This can help to simplify validating data and error checking. Validation can be performed manually or via integration with other specifications and frameworks, such as CDI, JPA, or JSF. To set rules on data, constraints are applied using annotations or XML configuration files. Bean Validation provides both built-in constraints and the ability to create custom constraints.

=== What's new in Bean Validation 2.0

Several new built in constraints were added in Bean Validation 2.0, including `@Email`, `@NotBlank`, `@Past`, and `@Negative`. Additionally, the ability to specify constraints on type parameters was added.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished bean validation application. Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install
mvn liberty:start-server

```

Point your browser to the `http://localhost:9080/LibertyProject` URL. You will see a web form for filling in information about an astronaut and spacecraft. The form accepts a name for the astronaut which must not be blank, an age which must between 18 and 100, and a correctly formatted email address. It also accepts a serial number for the spacecraft of the form "Liberty" followed by 4 integers. Try to input various data that meets and violates the constraints. When the data is valid no errors will appear on the screen, but when invalid data is input a message will appear next to the item in the form detailing why the data is invalid.

Once you are done stop the Open Liberty server:

```
mvn liberty:stop-server
```
Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Applying Constraints
// =================================================================================================
== Applying Constraints

First, the JavaBeans that will be constrained need to be created. Create the class for the Astronaut bean: `src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java`.

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java[tags=!copyright]
----

The bean stores the following attributes of an Astronaut: `name`, `age`, and `emailAddress`, along with providing getters and setters to access and set those values. This will need to be a CDI managed bean to allow for JSF integration so a scope needs to be specified, in this case `@RequestScoped`.

Let's say that it is required for a name to be specified. Bean Validation 2.0 provides a built-in constraint to check for this, `@NotBlank`, which ensures the value is not null or the empty String. The annotation is applied to the `name` field.

While in this example the annotation is placed on the field value itself, it can also be placed on the getter method, which has the same effect.

Another new built-in constraint in Bean Validation 2.0 is `@Email`, which can be used to validate that the Astronaut has been supplied a correctly formatted email address. The annotation is applied to the 'email' field.

Bean Validation allows for multiple constraints to be specified on a single field. Ensure that the astronaut is between the ages of 18 and 100 using the built-in constraints `@Min` and `@Max` on the 'age' field.

Next, create another class to represent a spacecraft: `src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java`.

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java[tags=!copyright]
----

The Spacecraft bean also contains three fields: `astronaut`, `serialNumber`, and `destination`. This will need to be a CDI managed bean to allow for JSF integration so a scope needs to be specified, in this case `@RequestScoped`. Another reason this needs to be a CDI managed bean is that method-level validation will be used on this JavaBean, which utilizes CDI interceptors.

New in Bean Validation 2.0, you can specify constraints on type parameters. Constrain the `destination` map so that the destination name is specified and the distance is positive, using `@NotBlank` and `@Positive`.

Since constraints have already been specified on the astronaut bean, there is no need to respecify those constraints in the spacecraft bean. Instead, by applying `@Valid` to the field, all the nested constraints on the astronaut bean will be validated.

In addition to specifying the built-in constraints, custom constraints can be created to allow for user defined validation rules. The `@SerialNumber` constraint applied to the `serialNumber` field is a custom constraint, which will be created later.

Bean Validation can also be used with CDI to provide method level validation. The method `launchSpacecraft` on the `Spacecraft` bean accepts a launchCode and if the launchCode is OpenLiberty it will return true that the spacecraft has launched. Otherwise it will return false.

This method utilizes both parameter and return value validation. The `@NotNull` on the parameter `launchCode` is used to validate that the parameter is not null before executing the method, eliminating the need to manually check the parameter within the method. Additionally, the method has a return level constraint `@AssertTrue`, to enforce that the boolean true must be returned.

To create the custom constraint for `@SerialNumber` begin by creating an `@interface` for a new annotation: `src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java`.

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java[tags=**;!copyright]
----

The `@Target` annotation indicates the element types to which this annotation can be applied. Since the constraint for `SerialNumber` will only be used on a field, the only target specified is `FIELD`. When defining a constraint annotation, it is required that the retention policy contains `RUNTIME`. The `@Constraint` annotation is used to specify the class that contains the validation logic for this annotation.

Looking at the body of `SerialNumber`, the `message()` method is used to provide the message that is output when a validation constraint is violated. The `groups()` and `payload()` methods can be used to associate this constraint only with certain groups or payloads, but the defaults will be used here.

Now, create the class that will provide the validation for this constraint: `src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java`.

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java[tags=**;!copyright]
----

There is one method in this class, `isValid()`, which is where the custom validation logic is supplied. In this case, the serial number must start with "Liberty" followed by four numbers, for example "Liberty0002". If the supplied serial number matches the constraint, `isValid` returns "true", else it returns "false".

Finally, create a servlet which can be used to programmatically validate the constraints on the spacecraft and astronaut JavaBeans: `src/main/java/io/openliberty/guides/beanvalidation/ValidatingServlet.java`.

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/ValidatingServlet.java[tags=**;!copyright]
----

There are two resources injected into the servlet, a validator and an instance of the spacecraft JavaBean. The default validator is used in this case and is obtained through resource injection, although a lookup or CDI injection could also be used. The spacecraft JavaBean is injected so that the method level constraints can be validated.

The programmatic validation takes place in the `processInputData` method. First, the spacecraft and astronaut beans are populated with the supplied data using the standard setters. To validate the data, `validate` is called on the spacecraft bean. Since spacecraft contains `@Valid` on astronaut, this will validate both beans. Any constraint violations found during the call to `validate` are returned as a set of `ConstraintViolation` objects.

A call is then made to `launchSpacecraft`, which will throw a `ConstraintViolationException` if either of the method-level constraints are violated.

// =================================================================================================
// Building and running the Application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Navigate to the following URL: `http://localhost:9080/LibertyProject`. To begin, enter the values below, which allow follow the previously defined constraints:

[source, role="no_copy"]
----
Name = Libby
Age = 25
Email = libbybot@openliberty.io
SerialNumber - Liberty0001
----

After clicking the submit button, you will not see any changes since no constraints have been violated. Now try the following values, all of which break the previously defined constraints:

[source, role="no_copy"]
----
Leave name blank
Age = 10
Email = libbybot
SerialNumber - Liberty1
----

After clicking submit, the constraint violation messages will be displayed:

[source, role="no_copy"]
----
Name: must not be blank
Age: must be greater than or equal to 18
Email Address: must be a well-formed email address
Serial Number: Serial number is not valid.
----

The form was created using JSF, which has built-in integration with Bean Validation.

include::{common-includes}/mvncompile.adoc[]

// =================================================================================================
// Testing the Constraints
// =================================================================================================
== Testing the Constraints

Now, write a couple of automated tests which will drive the previously created servlet. There is a test class provided at `src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java`. The test class already contains some utility methods and four blank test methods.

The first test will test that no constraint violations are found when the correct data is supplied. Add the method for `testNoFieldLevelConstraintViolations` as below:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java[tags=testNoFieldLevelConstraintViolations]
----

The data supplied to the beans in this test should pass all the previously defined constraints, so no constraint violations are expected.

The second test is much like the first, except data violating some of the constraints will be supplied. Add the method for `testNoFieldLevelConstraintViolations`:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java[tags=testNoFieldLevelConstraintViolations]
----

Since there are 3 constraint violations, there are three `ConstraintViolation` objects returned as a set from the call to `validate`.  The 3 expected messages are "must be greater than 0" for the negative distance specified in the destination map, "must be a well-formed email address" for the incorrect email address, and the custom "Serial number is not valid" message for the serial number.

The third test verifies the method level constraints specified on the `launchSpacecraft` method of the spacecraft bean are validated when the method is called with no violations.  Specify `testNoMethodLevelConstraintViolations`:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java[tags=testNoMethodLevelConstraintViolations]
----

In this test, the call to launchSpacecraft is made with the argument `OpenLiberty`, which results in `true` being retuned, which passes the specified constraint.

The fourth test validates that a `ConstraintViolationException` is thrown when one of the method level constraints is violated.  Specify `testMethodLevelConstraintViolation`:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java[tags=testMethodLevelConstraintViolation]
----

A call is made to the `launchSpacecraft` method of the spacecraft bean with an incorrect parameter, in this case "incorrectCode". Since this results in the method returning false, which violates the defined constraint, a `ConstraintViolationException` is thrown. The exception should include the constraint violation message, which in this case should include `must be true`.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.beanvalidation.BeanValidationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.493 sec - in it.io.openliberty.guides.beanvalidation.BeanValidationTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Great work! You're done!

You developed and tested a Java application utilizing Bean Validation 2.0 and Open Liberty.

include::{common-includes}/finish.adoc[]
