// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//  https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
:page-layout: guide
:projectid: bean-validation
:page-duration: 20 minutes
:page-releasedate: 2018-02-05
:page-description: Learn how to validate JavaBeans using Bean Validation and Open Liberty.
:page-tags: ['Java', 'Bean Validation', 'CDI', 'JSF', `@Email`, '@Min', '@Max', '@NotBlank', '@Positive', '@Valid', '@NotNull', '@AssertTrue', 'Custom Constraint']
:page-permalink: /guides/{projectid}
:page-related-guides: ['guide-cdi-intro']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Creating an application with Bean Validation

You'll explore how to use Bean Validation in Open Liberty to create an application to validate data.

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

You will learn the basics of writing and testing an application that uses Bean Validation, a
functionality of Bean Validation 2.0. The
application uses Bean Validation to validate data from a form or servlet request and to
ensure that the request meets the defined constraints.

=== What is Bean Validation?

Bean Validation is a Java specification that simplifies data validation and error checking. Bean Validation uses a standard way to validate data stored in JavaBeans. Validation can be performed manually
or with integration with other specifications and frameworks, such as CDI, JPA, or JSF. To set rules
on data, apply constraints by using annotations or XML configuration files. Bean Validation
provides both built-in constraints and the ability to create custom constraints. Bean Validation
allows for validation of both JavaBean fields and methods. For method-level validation, both the
input parameters and return value can be validated.

=== What's new in Bean Validation 2.0

Several built-in constraints are included in Bean Validation 2.0, such as `@Email`,
`@NotBlank`, `@Past`, and `@Negative`. You can also specify constraints on type
parameters.

The example application uses both field-level and method-level validation as well as
several of the built-in constraints and a custom constraint.

// =================================================================================================
// Getting Started
// =================================================================================================

include::{common-includes}/gitclone.adoc[]

=== Try what you'll build

The `finish` directory in the root of this guide contains the finished Bean Validation application.
Feel free to give it a try before you proceed with building your own.

To try out the application, first navigate to the `finish` directory and then execute the following
Maven goals to build the application and run it inside Open Liberty:

```
mvn clean install
mvn liberty:start-server

```

Point your browser to the `http://localhost:9080/Spacecraft` URL. You see a web form for
filling in information about an astronaut and spacecraft. The form accepts an astronaut name
that cannot be blank, an age that must be between 18 and 100, and a correctly formatted email
address. The form also accepts a serial number for the spacecraft that consists of `Liberty` followed by 4
integers. Input data that meets and violates the constraints. When the data is valid,
no errors appear on the screen, but when data is invalid, a message appears that details why the data is invalid.

When you are done, stop the Open Liberty server.

```
mvn liberty:stop-server
```
Now, navigate back to the `start` directory to begin.

// =================================================================================================
// Applying constraints on the JavaBeans
// =================================================================================================
== Applying constraints on the JavaBeans

First, create the JavaBeans to be constrained. Create the `Astronaut` bean class
in the `src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java` file:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/Astronaut.java[tags=!copyright]
----

The bean stores the attributes of an astronaut, `name`, `age`, and `emailAddress`, and
provides getters and setters to access and set the values. The JavaBean needs to be a CDI
managed bean to allow for JSF integration. A scope is necessary, as shown by the request
scope used in the example. To learn more about CDI, see https://openliberty.io/guides/cdi-intro.html[Injecting dependencies into microservices].

Apply the following constraints:

* The astronaut needs to have a name. Bean Validation 2.0 provides a built-in
`@NotBlank` constraint, which ensures the value is not null and contains one non-whitespace
character. Apply the annotation to the `name` field.

* The email supplied needs to be a valid email address. Another built-in constraint
in Bean Validation 2.0 is `@Email`, which can validate that the
`Astronaut` bean includes a correctly formatted email address. Apply the annotation to the `email` field.

* The astronaut needs to be between 18 and 100 years old. Bean Validation allows you to specify
multiple constraints on a single field. Ensure that the astronaut is between the
ages of 18 and 100 by using the `@Min` and `@Max` built-in constraints on the `age` field.

In this example, place the annotation on the field value itself. You can also place the annotation
on the getter method, which has the same effect.

Create another class to represent a spacecraft in the
`src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java` file:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/Spacecraft.java[tags=!copyright]
----

The `Spacecraft` bean contains three fields, `astronaut`, `serialNumber`, and `destination`.
The JavaBean needs to be a CDI managed bean to allow for JSF integration. A scope is necessary, as shown by the request
scope used in the example.
You also use method-level validation on this JavaBean, and method-level validation uses CDI interceptors.

Apply the following constraints:

* Every destination that is specified needs a name and a positive distance. In Bean
Validation 2.0, you can specify constraints on type parameters. Use the `@NotBlank` and
`@Positive` constraints to constrain the `destination` map so
that the destination name is not blank, and the distance is positive. Use the `@Positive` constraint to ensure that numeric value fields
are greater than 0.

* Supply a correctly formatted serial number. In addition to
specifying the built-in constraints, you can create custom constraints to allow user-defined
validation rules. The `@SerialNumber` constraint that is applied to the `serialNumber` field
is a custom constraint, which will be created later.

Because you already specified constraints on the `Astronaut` bean, the constraints do not need to
be respecified in the `Spacecraft` bean. Instead, by applying the `@Valid` annotation to the field,
all the nested constraints on the `Astronaut` bean are validated.

You can also use Bean Validation with CDI to provide method-level validation. The
`launchSpacecraft` method on the `Spacecraft` bean accepts a `launchCode` parameter, and if the `launchCode` parameter is
`OpenLiberty`, the parameter returns `true` that the spacecraft is launched. Otherwise, the parameter returns `false`.
The `launchSpacecraft` method uses both parameter and return value validation. The `@NotNull` constraint eliminates the need to manually check the parameter within the method. Use the `@NotNull` constraint
on the `launchCode` parameter to validate that the parameter is not null before the parameter executes
the method. Additionally,
the method has the `@AssertTrue` return-level constraint to enforce that the method must return the
`true` boolean.

// =================================================================================================
// Creating custom constraints
// =================================================================================================
== Creating custom constraints

To create the custom constraint for `@SerialNumber`, begin by creating an annotation in the
`src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java` file:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumber.java[tags=**;!copyright]
----

The `@Target` annotation indicates the element types to which you can apply the custom constraint. Because
the `SerialNumber` constraint is used only on a field, only the `FIELD` target is specified.

When you define a constraint annotation, the specification requires the `RUNTIME` retention policy.

Use the `@Constraint` annotation to specify the class that contains the validation
logic for the custom constraint.

In the `SerialNumber` body, the `message()` method provides the message that
is output when a validation constraint is violated. Use the `groups()` and `payload()` methods
to associate this constraint only with certain groups or payloads. The defaults are used
in the example.

Now, create the class that provides the validation for the `@SerialNumber` constraint in the
`src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java` file:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/SerialNumberValidator.java[tags=**;!copyright]
----

The `SerialNumberValidator` class has one method, `isValid()`, which contains the custom
validation logic. In this case, the serial number must start with `Liberty` followed by four
numbers, such as `Liberty0001`. If the supplied serial number matches the constraint,
`isValid` returns `true`. If the serial number does not match, it returns `false`.

// =================================================================================================
// Programmatically validating constraints
// =================================================================================================
== Programmatically validating constraints

Finally, create a servlet that can be used to programmatically validate the constraints on the
`Spacecraft` and `Astronaut` JavaBeans in the
`src/main/java/io/openliberty/guides/beanvalidation/ValidatingServlet.java` file:

[source,java]
----
include::finish/src/main/java/io/openliberty/guides/beanvalidation/ValidatingServlet.java[tags=**;!copyright]
----

Two resources, a validator and an instance of the `Spacecraft`
JavaBean, are injected into the servlet. The default validator is used and is obtained through resource injection.
However, you can also obtain the default validator with CDI injection or a JNDI lookup. The `Spacecraft` JavaBean
is injected so that the method-level constraints can be validated.

The programmatic validation takes place in the `processInputData` method. First, the `Spacecraft`
and `Astronaut` beans are populated with the supplied data using the standard setters. To validate
the data, the `validate` method is called on with the `Spacecraft` bean. Because the `Spacecraft` bean
contains the `@Valid` constraint on the `Astronaut` bean, both JavaBeans are validated. Any constraint
violations found during the call to the `validate` method are returned as a set of
`ConstraintViolation` objects.

A call is then made to the `launchSpacecraft` method, which throws a
`ConstraintViolationException` exception if either of the method-level constraints is violated.

// =================================================================================================
// Building and running the application
// =================================================================================================

include::{common-includes}/mvnbuild.adoc[]

Navigate to the `http://localhost:9080/Spacecraft` URL. Enter the following values, which pass the previously defined constraints:

[source, role="no_copy"]
----
Name = Libby
Age = 25
Email = libbybot@openliberty.io
SerialNumber = Liberty0001
----

After you click the `Submit` button, you don't see any changes because no constraint
violations appear. Next, enter the following values, all of which break the previously defined constraints:

[source, role="no_copy"]
----
Leave name blank
Age = 10
Email = libbybot
SerialNumber = Liberty1
----

After you click `Submit`, the constraint violation messages display:

[source, role="no_copy"]
----
Name: must not be blank
Age: must be greater than or equal to 18
Email Address: must be a well-formed email address
Serial Number: serial number is not valid.
----

The form was created with JSF, which has built-in integration with Bean Validation.

include::{common-includes}/mvncompile.adoc[]

// =================================================================================================
// Testing the constraints
// =================================================================================================
== Testing the constraints

Now, write automated tests to drive the previously created servlet. Create the
test class in the `src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java`
file:

[source,java]
----
include::finish/src/test/java/it/io/openliberty/guides/beanvalidation/BeanValidationTest.java[tags=**;!copyright]
----

Place the `@BeforeClass` annotation on a method that runs before any of the test cases. The `oneTimeSetup` method retrieves the port number for the Open Liberty server and builds a
base URL string that is used throughout the tests, which are described as follows:

* The `testNoFieldLevelConstraintViolations` test case verifies that no constraint violations occur when data is
supplied to the `Astronaut` and `Spacecraft` bean attributes.

* The `testFieldLevelConstraintViolation` test case verifies that the appropriate constraint violations occur
when data that is supplied to the `Astronaut` and `Spacecraft` attributes violates the defined constraints.
Because three constraint violations are defined, three `ConstraintViolation` objects are returned as a set
from the `validate` call. The three expected messages are `must be greater than 0` for the negative
distance specified in the destination map, `must be a well-formed email address` for the incorrect
email address, and the custom `serial number is not valid` message for the serial number.

* The `testNoMethodLevelConstraintViolations` test case verifies that the method-level constraints that are specified on
the `launchSpacecraft` method of the `Spacecraft` bean are validated when the method is called with
no violations. In this test, the call to the `launchSpacecraft` method is made with the `OpenLiberty` argument.
A value of `true` is retuned, which passes the specified constraints.

* The `testMethodLevelConstraintViolation` test case verifies that a `ConstraintViolationException` exception is thrown
when one of the method-level constraints is violated. A call with an incorrect parameter, such as `incorrectCode`, is made to the `launchSpacecraft` method of the `Spacecraft` bean. The method returns `false`, which violates the defined constraint, and a
`ConstraintViolationException` exception is thrown. The exception includes the constraint violation
message, which is `must be true` in this example.

include::{common-includes}/mvnverify.adoc[]

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.beanvalidation.BeanValidationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.493 sec - in
it.io.openliberty.guides.beanvalidation.BeanValidationTest

Results :

Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
----

== Great work! You're done!

You developed and tested a Java application by using Bean Validation 2.0 and Open Liberty.

include::{common-includes}/finish.adoc[]
